---
- name: Delete *.sql.gz files older than defined
  ansible.builtin.find:
    paths: "{{ mariadb_backup_restore_folder_backup }}"
    patterns: "*.sql.gz"
    age: "{{ mariadb_backup_restore_retention }}"
    recurse: false
  register: old_backups

- name: Remove old backup files
  ansible.buitin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_backups.files }}"
...
